pipeline {
  agent any
  environment {
    OPENAI_API_KEY=credentials('openai-api-key')
  }
  stages {
    stage('verify promptfoo installation') {
      steps {
        sh 'promptfoo --version help'
      }
    }
    stage('run the evaluation') {
      steps {
        dir('03-simple-test') {
          sh 'promptfoo eval'
        }
      }
    }
  }
}