pipeline {
  agent any
  environment {
    OPENAI_API_KEY=credentials('openai-api-key')
    PROMPTFOO_PYTHON="/Library/Frameworks/Python.framework/Versions/3.11/bin/python3"
  }
  stages {
    stage('verify promptfoo installation') {
      steps {
        sh 'promptfoo --version help'
      }
    }
    stage('run the evaluation') {
      steps {
        dir('03-simple-test') {
          sh 'promptfoo eval'
        }
      }
    }
  }
  post {
    always {
      archiveArtifacts artifacts: 'output.csv', followSymlinks: false
    }
  }
}