pipeline {
  agent any
  environment {
    OPENAI_API_KEY=credentials('openai-api-key')
  }
  stages {
    stage('verify promptfoo installation') {
      steps {
        sh 'promptfoo --version help'
      }
    }
    stage('run the evaluation') {
      steps {
        dir('04-multiple-translations-scenarios') {
          sh 'promptfoo eval'
        }
      }
    }
  }
  post {
    always {
      dir('04-multiple-translations-scenarios') {
        archiveArtifacts artifacts: 'output.html', followSymlinks: false
      }
    }
  }
}