pipeline {
  agent { 
    label 'promptfoo'
  }
  environment {
    OPENAI_API_KEY=credentials('openai-api-key')
  }
  stages {
    stage('verify promptfoo installation') {
      steps {
        sh 'promptfoo --version help'
      }
    }
    stage('run the evaluation') {
      steps {
        dir('01-simple-cli') {
          sh 'promptfoo eval'
        }
      }
    }
  }
}